# encoding:utf-8
from .local_config import SQLALCHEMY_BINDS, SQLALCHEMY_DATABASE_URI, SECRET_KEY


class DefaultConfig(object):
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI # 默认数据库
    
    # 需要绑定的多个数据库
    SQLALCHEMY_BINDS = SQLALCHEMY_BINDS
    PER_PAGE = 30  # 分页每页的个数
    SECRET_KEY = SECRET_KEY

    # 缓存配置（文件系统缓存）
    FILESYSTEM = {
		'CACHE_TYPE': 'filesystem',
		'CACHE_DIR': './flask_cache',
		'CACHE_DEFAULT_TIMEOUT': 922337203685477580,
		'CACHE_THRESHOLD': 922337203685477580
	}
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SESSION_TIME = 30*60
    EXPIRATION = 60*60*24  # auth有效期1天
