"""empty message

Revision ID: 199a17e9603f
Revises: 638400b9448d
Create Date: 2021-03-07 17:16:31.235510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199a17e9603f'
down_revision = '638400b9448d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_like_lunyu_uid'), 'like_lunyu', ['uid'], unique=False)
    op.create_index(op.f('ix_like_poem_uid'), 'like_poem', ['uid'], unique=False)
    op.create_index(op.f('ix_like_shijing_uid'), 'like_shijing', ['uid'], unique=False)
    op.create_index(op.f('ix_like_songci_uid'), 'like_songci', ['uid'], unique=False)
    op.create_foreign_key(None, 'lun_yu', 'like_lunyu', ['u_id'], ['uid'])
    op.add_column('poems', sa.Column('u_id', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'poems', 'like_poem', ['u_id'], ['uid'])
    op.add_column('shi_jing', sa.Column('u_id', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'shi_jing', 'like_shijing', ['u_id'], ['uid'])
    op.add_column('song_ci', sa.Column('u_id', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'song_ci', 'like_songci', ['u_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song_ci', type_='foreignkey')
    op.drop_column('song_ci', 'u_id')
    op.drop_constraint(None, 'shi_jing', type_='foreignkey')
    op.drop_column('shi_jing', 'u_id')
    op.drop_constraint(None, 'poems', type_='foreignkey')
    op.drop_column('poems', 'u_id')
    op.drop_constraint(None, 'lun_yu', type_='foreignkey')
    op.drop_index(op.f('ix_like_songci_uid'), table_name='like_songci')
    op.drop_index(op.f('ix_like_shijing_uid'), table_name='like_shijing')
    op.drop_index(op.f('ix_like_poem_uid'), table_name='like_poem')
    op.drop_index(op.f('ix_like_lunyu_uid'), table_name='like_lunyu')
    # ### end Alembic commands ###
