"""empty message

Revision ID: 24dc81bf4266
Revises: 
Create Date: 2021-01-02 22:36:51.019247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dc81bf4266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('solve', sa.String(length=100), nullable=True),
    sa.Column('comment_type', sa.String(length=10), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('can_show', sa.Boolean(), nullable=True),
    sa.Column('is_useful', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_comment_type'), 'comment', ['comment_type'], unique=False)
    op.create_index(op.f('ix_comment_email'), 'comment', ['email'], unique=False)
    op.create_table('dwz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(length=65536), nullable=True),
    sa.Column('dwz', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dwz_dwz'), 'dwz', ['dwz'], unique=True)
    op.create_table('poem_ci_poet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_desc', sa.Text(length=16777216), nullable=True),
    sa.Column('long_desc_sim', sa.Text(length=16777216), nullable=True),
    sa.Column('short_desc', sa.Text(length=65536), nullable=True),
    sa.Column('short_desc_sim', sa.Text(length=65536), nullable=True),
    sa.Column('poet', sa.String(length=100), nullable=True),
    sa.Column('poet_sim', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_ci_poet_poet'), 'poem_ci_poet', ['poet'], unique=False)
    op.create_index(op.f('ix_poem_ci_poet_poet_sim'), 'poem_ci_poet', ['poet_sim'], unique=False)
    op.create_table('poem_lun_yu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(length=65536), nullable=True),
    sa.Column('paragraphs_sim', sa.Text(length=65536), nullable=True),
    sa.Column('chapter', sa.String(length=50), nullable=True),
    sa.Column('chapter_sim', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_lun_yu_chapter'), 'poem_lun_yu', ['chapter'], unique=False)
    op.create_index(op.f('ix_poem_lun_yu_chapter_sim'), 'poem_lun_yu', ['chapter_sim'], unique=False)
    op.create_table('poem_poet_introduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descb', sa.Text(length=16777216), nullable=True),
    sa.Column('descb_sim', sa.Text(length=16777216), nullable=True),
    sa.Column('poet', sa.String(length=100), nullable=True),
    sa.Column('poet_sim', sa.String(length=100), nullable=True),
    sa.Column('dynasty', sa.String(length=8), nullable=True),
    sa.Column('dynasty_sim', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_poet_introduction_dynasty'), 'poem_poet_introduction', ['dynasty'], unique=False)
    op.create_index(op.f('ix_poem_poet_introduction_dynasty_sim'), 'poem_poet_introduction', ['dynasty_sim'], unique=False)
    op.create_index(op.f('ix_poem_poet_introduction_poet'), 'poem_poet_introduction', ['poet'], unique=False)
    op.create_index(op.f('ix_poem_poet_introduction_poet_sim'), 'poem_poet_introduction', ['poet_sim'], unique=False)
    op.create_table('poem_shi_jing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poem', sa.Text(length=16777216), nullable=True),
    sa.Column('poem_sim', sa.Text(length=16777216), nullable=True),
    sa.Column('chapter', sa.String(length=30), nullable=True),
    sa.Column('chapter_sim', sa.String(length=30), nullable=True),
    sa.Column('section', sa.String(length=30), nullable=True),
    sa.Column('section_sim', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(length=65536), nullable=True),
    sa.Column('content_sim', sa.Text(length=65536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_shi_jing_chapter'), 'poem_shi_jing', ['chapter'], unique=False)
    op.create_index(op.f('ix_poem_shi_jing_chapter_sim'), 'poem_shi_jing', ['chapter_sim'], unique=False)
    op.create_index(op.f('ix_poem_shi_jing_section'), 'poem_shi_jing', ['section'], unique=False)
    op.create_index(op.f('ix_poem_shi_jing_section_sim'), 'poem_shi_jing', ['section_sim'], unique=False)
    op.create_table('poem_song_ci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(length=16777216), nullable=True),
    sa.Column('paragraphs_sim', sa.Text(length=16777216), nullable=True),
    sa.Column('rhythmic', sa.String(length=40), nullable=True),
    sa.Column('rhythmic_sim', sa.String(length=40), nullable=True),
    sa.Column('poet', sa.String(length=100), nullable=True),
    sa.Column('poet_sim', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_song_ci_poet'), 'poem_song_ci', ['poet'], unique=False)
    op.create_index(op.f('ix_poem_song_ci_poet_sim'), 'poem_song_ci', ['poet_sim'], unique=False)
    op.create_index(op.f('ix_poem_song_ci_rhythmic'), 'poem_song_ci', ['rhythmic'], unique=False)
    op.create_index(op.f('ix_poem_song_ci_rhythmic_sim'), 'poem_song_ci', ['rhythmic_sim'], unique=False)
    op.create_table('poem_tang_song_poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(), nullable=True),
    sa.Column('paragraphs_sim', sa.Text(), nullable=True),
    sa.Column('poem', sa.Text(length=65536), nullable=True),
    sa.Column('poem_sim', sa.Text(length=65536), nullable=True),
    sa.Column('poet', sa.String(length=100), nullable=True),
    sa.Column('poet_sim', sa.String(length=100), nullable=True),
    sa.Column('dynasty', sa.String(length=8), nullable=True),
    sa.Column('dynasty_sim', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_tang_song_poem_dynasty'), 'poem_tang_song_poem', ['dynasty'], unique=False)
    op.create_index(op.f('ix_poem_tang_song_poem_dynasty_sim'), 'poem_tang_song_poem', ['dynasty_sim'], unique=False)
    op.create_index(op.f('ix_poem_tang_song_poem_poet'), 'poem_tang_song_poem', ['poet'], unique=False)
    op.create_index(op.f('ix_poem_tang_song_poem_poet_sim'), 'poem_tang_song_poem', ['poet_sim'], unique=False)
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user_user', ['email'], unique=True)
    op.create_table('words_cet4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_cet4_word'), 'words_cet4', ['word'], unique=False)
    op.create_table('words_cet6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_cet6_word'), 'words_cet6', ['word'], unique=False)
    op.create_table('words_daily_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_daily_words_word'), 'words_daily_words', ['word'], unique=False)
    op.create_table('words_gre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_gre_word'), 'words_gre', ['word'], unique=False)
    op.create_table('words_toefl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_toefl_word'), 'words_toefl', ['word'], unique=False)
    op.create_table('user_config',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('words_book', sa.String(length=10), nullable=True),
    sa.Column('words_num', sa.Integer(), nullable=True),
    sa.Column('role', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('user_memo',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(length=16777216), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_memo')
    op.drop_table('user_config')
    op.drop_index(op.f('ix_words_toefl_word'), table_name='words_toefl')
    op.drop_table('words_toefl')
    op.drop_index(op.f('ix_words_gre_word'), table_name='words_gre')
    op.drop_table('words_gre')
    op.drop_index(op.f('ix_words_daily_words_word'), table_name='words_daily_words')
    op.drop_table('words_daily_words')
    op.drop_index(op.f('ix_words_cet6_word'), table_name='words_cet6')
    op.drop_table('words_cet6')
    op.drop_index(op.f('ix_words_cet4_word'), table_name='words_cet4')
    op.drop_table('words_cet4')
    op.drop_index(op.f('ix_user_user_email'), table_name='user_user')
    op.drop_table('user_user')
    op.drop_index(op.f('ix_poem_tang_song_poem_poet_sim'), table_name='poem_tang_song_poem')
    op.drop_index(op.f('ix_poem_tang_song_poem_poet'), table_name='poem_tang_song_poem')
    op.drop_index(op.f('ix_poem_tang_song_poem_dynasty_sim'), table_name='poem_tang_song_poem')
    op.drop_index(op.f('ix_poem_tang_song_poem_dynasty'), table_name='poem_tang_song_poem')
    op.drop_table('poem_tang_song_poem')
    op.drop_index(op.f('ix_poem_song_ci_rhythmic_sim'), table_name='poem_song_ci')
    op.drop_index(op.f('ix_poem_song_ci_rhythmic'), table_name='poem_song_ci')
    op.drop_index(op.f('ix_poem_song_ci_poet_sim'), table_name='poem_song_ci')
    op.drop_index(op.f('ix_poem_song_ci_poet'), table_name='poem_song_ci')
    op.drop_table('poem_song_ci')
    op.drop_index(op.f('ix_poem_shi_jing_section_sim'), table_name='poem_shi_jing')
    op.drop_index(op.f('ix_poem_shi_jing_section'), table_name='poem_shi_jing')
    op.drop_index(op.f('ix_poem_shi_jing_chapter_sim'), table_name='poem_shi_jing')
    op.drop_index(op.f('ix_poem_shi_jing_chapter'), table_name='poem_shi_jing')
    op.drop_table('poem_shi_jing')
    op.drop_index(op.f('ix_poem_poet_introduction_poet_sim'), table_name='poem_poet_introduction')
    op.drop_index(op.f('ix_poem_poet_introduction_poet'), table_name='poem_poet_introduction')
    op.drop_index(op.f('ix_poem_poet_introduction_dynasty_sim'), table_name='poem_poet_introduction')
    op.drop_index(op.f('ix_poem_poet_introduction_dynasty'), table_name='poem_poet_introduction')
    op.drop_table('poem_poet_introduction')
    op.drop_index(op.f('ix_poem_lun_yu_chapter_sim'), table_name='poem_lun_yu')
    op.drop_index(op.f('ix_poem_lun_yu_chapter'), table_name='poem_lun_yu')
    op.drop_table('poem_lun_yu')
    op.drop_index(op.f('ix_poem_ci_poet_poet_sim'), table_name='poem_ci_poet')
    op.drop_index(op.f('ix_poem_ci_poet_poet'), table_name='poem_ci_poet')
    op.drop_table('poem_ci_poet')
    op.drop_index(op.f('ix_dwz_dwz'), table_name='dwz')
    op.drop_table('dwz')
    op.drop_index(op.f('ix_comment_email'), table_name='comment')
    op.drop_index(op.f('ix_comment_comment_type'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
