"""empty message

Revision ID: 638400b9448d
Revises: 
Create Date: 2021-03-06 20:45:50.625518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638400b9448d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_poet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_desc', sa.Text(), nullable=True),
    sa.Column('short_desc', sa.Text(), nullable=True),
    sa.Column('poet', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_poet_poet'), 'ci_poet', ['poet'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('solve', sa.String(length=100), nullable=True),
    sa.Column('comment_type', sa.String(length=10), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('can_show', sa.Boolean(), nullable=True),
    sa.Column('is_useful', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_comment_type'), 'comment', ['comment_type'], unique=False)
    op.create_index(op.f('ix_comment_email'), 'comment', ['email'], unique=False)
    op.create_table('dwz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(length=65536), nullable=True),
    sa.Column('dwz', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dwz_dwz'), 'dwz', ['dwz'], unique=True)
    op.create_table('lun_yu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(length=65536), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lun_yu_chapter'), 'lun_yu', ['chapter'], unique=False)
    op.create_table('poets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poet', sa.String(length=32), nullable=True),
    sa.Column('dynasty', sa.String(length=8), nullable=True),
    sa.Column('descb', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poets_dynasty'), 'poets', ['dynasty'], unique=False)
    op.create_index(op.f('ix_poets_poet'), 'poets', ['poet'], unique=False)
    op.create_table('shi_jing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poem', sa.Text(), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shi_jing_chapter'), 'shi_jing', ['chapter'], unique=False)
    op.create_index(op.f('ix_shi_jing_section'), 'shi_jing', ['section'], unique=False)
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user_user', ['email'], unique=True)
    op.create_table('words_cet4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_cet4_word'), 'words_cet4', ['word'], unique=False)
    op.create_table('words_cet6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_cet6_word'), 'words_cet6', ['word'], unique=False)
    op.create_table('words_daily_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_daily_words_word'), 'words_daily_words', ['word'], unique=False)
    op.create_table('words_gre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_gre_word'), 'words_gre', ['word'], unique=False)
    op.create_table('words_toefl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('spellingA', sa.String(length=64), nullable=True),
    sa.Column('spellingE', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_toefl_word'), 'words_toefl', ['word'], unique=False)
    op.create_table('poems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(), nullable=True),
    sa.Column('poem', sa.Text(), nullable=True),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poet_id'], ['poets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_ci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(), nullable=True),
    sa.Column('rhythmic', sa.String(length=64), nullable=True),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poet_id'], ['ci_poet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_ci_rhythmic'), 'song_ci', ['rhythmic'], unique=False)
    op.create_table('user_config',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('words_book', sa.String(length=10), nullable=True),
    sa.Column('words_num', sa.Integer(), nullable=True),
    sa.Column('role', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('user_memo',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(length=16777216), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_memo')
    op.drop_table('user_config')
    op.drop_index(op.f('ix_song_ci_rhythmic'), table_name='song_ci')
    op.drop_table('song_ci')
    op.drop_table('poems')
    op.drop_index(op.f('ix_words_toefl_word'), table_name='words_toefl')
    op.drop_table('words_toefl')
    op.drop_index(op.f('ix_words_gre_word'), table_name='words_gre')
    op.drop_table('words_gre')
    op.drop_index(op.f('ix_words_daily_words_word'), table_name='words_daily_words')
    op.drop_table('words_daily_words')
    op.drop_index(op.f('ix_words_cet6_word'), table_name='words_cet6')
    op.drop_table('words_cet6')
    op.drop_index(op.f('ix_words_cet4_word'), table_name='words_cet4')
    op.drop_table('words_cet4')
    op.drop_index(op.f('ix_user_user_email'), table_name='user_user')
    op.drop_table('user_user')
    op.drop_index(op.f('ix_shi_jing_section'), table_name='shi_jing')
    op.drop_index(op.f('ix_shi_jing_chapter'), table_name='shi_jing')
    op.drop_table('shi_jing')
    op.drop_index(op.f('ix_poets_poet'), table_name='poets')
    op.drop_index(op.f('ix_poets_dynasty'), table_name='poets')
    op.drop_table('poets')
    op.drop_index(op.f('ix_lun_yu_chapter'), table_name='lun_yu')
    op.drop_table('lun_yu')
    op.drop_index(op.f('ix_dwz_dwz'), table_name='dwz')
    op.drop_table('dwz')
    op.drop_index(op.f('ix_comment_email'), table_name='comment')
    op.drop_index(op.f('ix_comment_comment_type'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_ci_poet_poet'), table_name='ci_poet')
    op.drop_table('ci_poet')
    # ### end Alembic commands ###
