"""empty message

Revision ID: e45c5a12e455
Revises: f93b3a6ac0f4
Create Date: 2021-01-03 10:56:36.031099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45c5a12e455'
down_revision = 'f93b3a6ac0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('song_ci_ibfk_1', 'song_ci', type_='foreignkey')
    op.create_foreign_key(None, 'song_ci', 'ci_poet', ['poet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song_ci', type_='foreignkey')
    op.create_foreign_key('song_ci_ibfk_1', 'song_ci', 'ci_poet', ['poet_id'], ['id'])
    # ### end Alembic commands ###
