"""empty message

Revision ID: f93b3a6ac0f4
Revises: 24dc81bf4266
Create Date: 2021-01-03 10:51:25.766171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f93b3a6ac0f4'
down_revision = '24dc81bf4266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_poet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_desc', sa.Text(), nullable=True),
    sa.Column('long_desc_sim', sa.Text(), nullable=True),
    sa.Column('short_desc', sa.Text(), nullable=True),
    sa.Column('short_desc_sim', sa.Text(), nullable=True),
    sa.Column('poet', sa.String(length=32), nullable=True),
    sa.Column('poet_sim', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_poet_poet'), 'ci_poet', ['poet'], unique=False)
    op.create_index(op.f('ix_ci_poet_poet_sim'), 'ci_poet', ['poet_sim'], unique=False)
    op.create_table('lun_yu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(length=65536), nullable=True),
    sa.Column('paragraphs_sim', sa.Text(length=65536), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('chapter_sim', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lun_yu_chapter'), 'lun_yu', ['chapter'], unique=False)
    op.create_index(op.f('ix_lun_yu_chapter_sim'), 'lun_yu', ['chapter_sim'], unique=False)
    op.create_table('poets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poet', sa.String(length=32), nullable=True),
    sa.Column('poet_sim', sa.String(length=32), nullable=True),
    sa.Column('dynasty', sa.String(length=8), nullable=True),
    sa.Column('dynasty_sim', sa.String(length=8), nullable=True),
    sa.Column('descb', sa.Text(), nullable=True),
    sa.Column('descb_sim', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poets_dynasty'), 'poets', ['dynasty'], unique=False)
    op.create_index(op.f('ix_poets_dynasty_sim'), 'poets', ['dynasty_sim'], unique=False)
    op.create_index(op.f('ix_poets_poet'), 'poets', ['poet'], unique=False)
    op.create_index(op.f('ix_poets_poet_sim'), 'poets', ['poet_sim'], unique=False)
    op.create_table('shi_jing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poem', sa.Text(), nullable=True),
    sa.Column('poem_sim', sa.Text(), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('chapter_sim', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('section_sim', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_sim', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shi_jing_chapter'), 'shi_jing', ['chapter'], unique=False)
    op.create_index(op.f('ix_shi_jing_chapter_sim'), 'shi_jing', ['chapter_sim'], unique=False)
    op.create_index(op.f('ix_shi_jing_section'), 'shi_jing', ['section'], unique=False)
    op.create_index(op.f('ix_shi_jing_section_sim'), 'shi_jing', ['section_sim'], unique=False)
    op.create_table('poems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(), nullable=True),
    sa.Column('paragraphs_sim', sa.Text(), nullable=True),
    sa.Column('poem', sa.Text(), nullable=True),
    sa.Column('poem_sim', sa.Text(), nullable=True),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poet_id'], ['poets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_ci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Text(length=16777216), nullable=True),
    sa.Column('paragraphs_sim', sa.Text(length=16777216), nullable=True),
    sa.Column('rhythmic', sa.String(length=40), nullable=True),
    sa.Column('rhythmic_sim', sa.String(length=40), nullable=True),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poet_id'], ['ci_poet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_ci_rhythmic'), 'song_ci', ['rhythmic'], unique=False)
    op.create_index(op.f('ix_song_ci_rhythmic_sim'), 'song_ci', ['rhythmic_sim'], unique=False)
    op.drop_index('ix_poem_ci_poet_poet', table_name='poem_ci_poet')
    op.drop_index('ix_poem_ci_poet_poet_sim', table_name='poem_ci_poet')
    op.drop_table('poem_ci_poet')
    op.drop_index('ix_poem_song_ci_poet', table_name='poem_song_ci')
    op.drop_index('ix_poem_song_ci_poet_sim', table_name='poem_song_ci')
    op.drop_index('ix_poem_song_ci_rhythmic', table_name='poem_song_ci')
    op.drop_index('ix_poem_song_ci_rhythmic_sim', table_name='poem_song_ci')
    op.drop_table('poem_song_ci')
    op.drop_index('ix_poem_poet_introduction_dynasty', table_name='poem_poet_introduction')
    op.drop_index('ix_poem_poet_introduction_dynasty_sim', table_name='poem_poet_introduction')
    op.drop_index('ix_poem_poet_introduction_poet', table_name='poem_poet_introduction')
    op.drop_index('ix_poem_poet_introduction_poet_sim', table_name='poem_poet_introduction')
    op.drop_table('poem_poet_introduction')
    op.drop_index('ix_poem_shi_jing_chapter', table_name='poem_shi_jing')
    op.drop_index('ix_poem_shi_jing_chapter_sim', table_name='poem_shi_jing')
    op.drop_index('ix_poem_shi_jing_section', table_name='poem_shi_jing')
    op.drop_index('ix_poem_shi_jing_section_sim', table_name='poem_shi_jing')
    op.drop_table('poem_shi_jing')
    op.drop_index('ix_poem_tang_song_poem_dynasty', table_name='poem_tang_song_poem')
    op.drop_index('ix_poem_tang_song_poem_dynasty_sim', table_name='poem_tang_song_poem')
    op.drop_index('ix_poem_tang_song_poem_poet', table_name='poem_tang_song_poem')
    op.drop_index('ix_poem_tang_song_poem_poet_sim', table_name='poem_tang_song_poem')
    op.drop_table('poem_tang_song_poem')
    op.drop_index('ix_poem_lun_yu_chapter', table_name='poem_lun_yu')
    op.drop_index('ix_poem_lun_yu_chapter_sim', table_name='poem_lun_yu')
    op.drop_table('poem_lun_yu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem_lun_yu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('paragraphs', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('paragraphs_sim', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('chapter', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('chapter_sim', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_poem_lun_yu_chapter_sim', 'poem_lun_yu', ['chapter_sim'], unique=False)
    op.create_index('ix_poem_lun_yu_chapter', 'poem_lun_yu', ['chapter'], unique=False)
    op.create_table('poem_tang_song_poem',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('paragraphs', mysql.TEXT(), nullable=True),
    sa.Column('paragraphs_sim', mysql.TEXT(), nullable=True),
    sa.Column('poem', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('poem_sim', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('poet', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poet_sim', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dynasty', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('dynasty_sim', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_poem_tang_song_poem_poet_sim', 'poem_tang_song_poem', ['poet_sim'], unique=False)
    op.create_index('ix_poem_tang_song_poem_poet', 'poem_tang_song_poem', ['poet'], unique=False)
    op.create_index('ix_poem_tang_song_poem_dynasty_sim', 'poem_tang_song_poem', ['dynasty_sim'], unique=False)
    op.create_index('ix_poem_tang_song_poem_dynasty', 'poem_tang_song_poem', ['dynasty'], unique=False)
    op.create_table('poem_shi_jing',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('poem', mysql.LONGTEXT(), nullable=True),
    sa.Column('poem_sim', mysql.LONGTEXT(), nullable=True),
    sa.Column('chapter', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('chapter_sim', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('section', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('section_sim', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('content_sim', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_poem_shi_jing_section_sim', 'poem_shi_jing', ['section_sim'], unique=False)
    op.create_index('ix_poem_shi_jing_section', 'poem_shi_jing', ['section'], unique=False)
    op.create_index('ix_poem_shi_jing_chapter_sim', 'poem_shi_jing', ['chapter_sim'], unique=False)
    op.create_index('ix_poem_shi_jing_chapter', 'poem_shi_jing', ['chapter'], unique=False)
    op.create_table('poem_poet_introduction',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('descb', mysql.LONGTEXT(), nullable=True),
    sa.Column('descb_sim', mysql.LONGTEXT(), nullable=True),
    sa.Column('poet', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poet_sim', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dynasty', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('dynasty_sim', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_poem_poet_introduction_poet_sim', 'poem_poet_introduction', ['poet_sim'], unique=False)
    op.create_index('ix_poem_poet_introduction_poet', 'poem_poet_introduction', ['poet'], unique=False)
    op.create_index('ix_poem_poet_introduction_dynasty_sim', 'poem_poet_introduction', ['dynasty_sim'], unique=False)
    op.create_index('ix_poem_poet_introduction_dynasty', 'poem_poet_introduction', ['dynasty'], unique=False)
    op.create_table('poem_song_ci',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('paragraphs', mysql.LONGTEXT(), nullable=True),
    sa.Column('paragraphs_sim', mysql.LONGTEXT(), nullable=True),
    sa.Column('rhythmic', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('rhythmic_sim', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('poet', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poet_sim', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_poem_song_ci_rhythmic_sim', 'poem_song_ci', ['rhythmic_sim'], unique=False)
    op.create_index('ix_poem_song_ci_rhythmic', 'poem_song_ci', ['rhythmic'], unique=False)
    op.create_index('ix_poem_song_ci_poet_sim', 'poem_song_ci', ['poet_sim'], unique=False)
    op.create_index('ix_poem_song_ci_poet', 'poem_song_ci', ['poet'], unique=False)
    op.create_table('poem_ci_poet',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('long_desc', mysql.LONGTEXT(), nullable=True),
    sa.Column('long_desc_sim', mysql.LONGTEXT(), nullable=True),
    sa.Column('short_desc', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('short_desc_sim', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('poet', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poet_sim', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_poem_ci_poet_poet_sim', 'poem_ci_poet', ['poet_sim'], unique=False)
    op.create_index('ix_poem_ci_poet_poet', 'poem_ci_poet', ['poet'], unique=False)
    op.drop_index(op.f('ix_song_ci_rhythmic_sim'), table_name='song_ci')
    op.drop_index(op.f('ix_song_ci_rhythmic'), table_name='song_ci')
    op.drop_table('song_ci')
    op.drop_table('poems')
    op.drop_index(op.f('ix_shi_jing_section_sim'), table_name='shi_jing')
    op.drop_index(op.f('ix_shi_jing_section'), table_name='shi_jing')
    op.drop_index(op.f('ix_shi_jing_chapter_sim'), table_name='shi_jing')
    op.drop_index(op.f('ix_shi_jing_chapter'), table_name='shi_jing')
    op.drop_table('shi_jing')
    op.drop_index(op.f('ix_poets_poet_sim'), table_name='poets')
    op.drop_index(op.f('ix_poets_poet'), table_name='poets')
    op.drop_index(op.f('ix_poets_dynasty_sim'), table_name='poets')
    op.drop_index(op.f('ix_poets_dynasty'), table_name='poets')
    op.drop_table('poets')
    op.drop_index(op.f('ix_lun_yu_chapter_sim'), table_name='lun_yu')
    op.drop_index(op.f('ix_lun_yu_chapter'), table_name='lun_yu')
    op.drop_table('lun_yu')
    op.drop_index(op.f('ix_ci_poet_poet_sim'), table_name='ci_poet')
    op.drop_index(op.f('ix_ci_poet_poet'), table_name='ci_poet')
    op.drop_table('ci_poet')
    # ### end Alembic commands ###
